.TH ELM-DOC "1" "June 2014" "User Commands"
.SH NAME
elm-doc - Generate documentation for Elm projects
.SH DESCRIPTION
Generate documentation for Elm, (c) Evan Czaplicki
.SH SYNOPSIS
elm-doc flags [OPTIONS] [FILES]
.IP
Generate documentation for Elm
.SS "Common flags:"
.TP
\-? \fB\-\-help\fR
Display help message
.TP
\fB\-V\fR \fB\-\-version\fR
Print version information
